### ISSUE TITLE
CKEditor shipped with Liferay 7.3.3 has broken mouse support

### ISSUE THREAD

**Issue by matthiasblaesing** [liferay/liferay-ckeditor#100]
I tested an upgrade for our systems and noticed, that the CKEditor as shipped with Liferay 7.3.3 does not allow mouse interaction with the test. I tested in Firefox (78) and Chrome (84).

Steps to reproduce:
--------------------
1. Fetch `liferay-ce-portal-tomcat-7.3.3-ga4-20200701015330959.tar.gz` from sourceforge (https://sourceforge.net/projects/lportal/files/Liferay%20Portal/7.3.3%20GA4/)
2. Uncompress the file and start the liferay system and run through basic setup
3. Shutdown the system
4. Add settings to `portal-setup-wizard.properties`:
```properties
editor.wysiwyg.default=ckeditor
editor.wysiwyg.portal-impl.portlet.ddm.text_html.ftl=ckeditor
editor.wysiwyg.portal-web.docroot.html.portlet.announcements.edit_entry.jsp=ckeditor
editor.wysiwyg.portal-web.docroot.html.portlet.blogs.edit_entry.jsp=ckeditor
editor.wysiwyg.portal-web.docroot.html.portlet.mail.edit.jsp=ckeditor
editor.wysiwyg.portal-web.docroot.html.portlet.mail.edit_message.jsp=ckeditor
editor.wysiwyg.portal-web.docroot.html.portlet.message_boards.edit_message.bb_code.jsp=ckeditor_bbcode
editor.wysiwyg.portal-web.docroot.html.portlet.message_boards.edit_message.html.jsp=ckeditor
editor.wysiwyg.portal-web.docroot.html.taglib.ui.discussion.jsp=ckeditor
editor.wysiwyg.portal-web.docroot.html.taglib.ui.email_notification_settings.jsp=ckeditor
```
5. Start liferay again
6. Create a new widget page
7. Add a new "Web Content Display" portlet to the page
8. Add a new "Basic Web Content", enter some lines of text, mark only a section of the text and try to format it as bold

Observation / Expected outcome
====================
The selection is not created, clicking the "Bold" icon toggles it, but the bold formatting is only applied to newly typed text. Creating the selection with the keyboard (move cursor with keys and creating selection by holding down shift and moving cursor with cursor keys) works and allows formatting.

I would expect, that clicking with mouse should move the cursor to the pointed location and dragging the mouse while mouse button is clicked should create a selection. Neither works.

This is a regression from 7.3.2 where the same worked correctly.

**Comment by markocikos** [comment]
Fixed in https://github.com/liferay/liferay-ckeditor/pull/98, under https://issues.liferay.com/browse/LPS-117288. Published in [`4.14.1-liferay.5`](https://github.com/liferay/liferay-ckeditor/releases/tag/v4.14.1-liferay.5), applied to portal in https://github.com/brianchandotcom/liferay-portal/pull/91749
