### ISSUE TITLE
Avoid plugin directories in the skin directory

### ISSUE THREAD

**Issue by julien** [liferay/liferay-ckeditor#103]
As discussed in #102 and more specifically [here](https://github.com/liferay/liferay-ckeditor/pull/102#discussion_r465605154), we should avoid putting plugin specific code in the `skins` directory, and place it under the `plugins` directory.

**Comment by carloslancha** [comment]
![image](https://media.giphy.com/media/11P9MoNgzYl9vy/giphy.gif)

**Comment by julien** [comment]
Fixed in #128
