### ISSUE TITLE
colorbutton removes scrollbar when used in Alloyeditor

### ISSUE THREAD

**Issue by fortunatomaldonado** [liferay/liferay-ckeditor#134]
https://issues.liferay.com/browse/LPS-121472

When Text Color is added to AlloyEditor, [`onblock`](https://github.com/ckeditor/ckeditor4/blob/major/plugins/colorbutton/plugin.js#L193) is called and removes a scrollbar.

It looks like this behavior can be fixed with a condition so that it will not change the intended behavior of CKEditor and fix the issue in AlloyEditor.

Let me know if there are any comments or questions about this.
Thank you.

**Comment by wincent** [comment]
The LPS sounds like a legit bug. Can you put together a PR for us to evaluate?

**Comment by fortunatomaldonado** [comment]
This issue is due to a third party plugin and it is up to the customer to address this. We provided assistance on where to address this issue [here.](https://github.com/liferay/alloy-editor/issues/749#issuecomment-306788867)
