### ISSUE TITLE
Add padding to active combo buttons to avoid flickering

### ISSUE THREAD

**Issue by orsolyaDekany** [liferay/liferay-ckeditor#147]
Hello,
**Reproduction steps:**
1) Edit portal-ext.properties to update the following portal property:
editor.wysiwyg.portal-impl.portlet.ddm.text_html.ftl=ckeditor
2) Start 7.2.x
3) Create a new Basic Web Content
4) Hover over the first of the second row (combo button)
**Result**: combo button is flickering
**Expected**: no flickering

![flickering](https://user-images.githubusercontent.com/69793575/102995437-53f90c80-4521-11eb-86f7-6c4b2d51a7db.gif)

https://issues.liferay.com/browse/LPP-39781

This issue is not present on master because of the combination of [LPS-107615](https://issues.liferay.com/browse/LPS-107615) and the latest liferay-ckeditor version "4.14.1-liferay.13"

The issue was introduced with liferay-ckeditor: "4.14.1-liferay.6" with this [PR](https://github.com/liferay/liferay-ckeditor/commit/63479e97b47bdc61aae3ce0ec69f55918401afc7).
Padding is added to combo button 6px 18px, however padding of active/hover/focus elements have not changed and it causes flickering on hover.

To fix this and to be alignment with other rows, I add padding on active combo button elements. Now we will not need any margin on combo_button element, so I removed that too. I will link the PR to this issue.
Thank you

**Comment by NemethNorbert** [comment]
https://github.com/liferay/liferay-ckeditor/pull/148

**Comment by julien** [comment]
Fixed in #148
