### ISSUE TITLE
AlloyEditor Source view no longer respects line breaks due to the missing htmlwriter plugin

### ISSUE THREAD

**Issue by NemethNorbert** [liferay/liferay-ckeditor#151]
https://issues.liferay.com/browse/LPS-126202
[htmlwriter](https://ckeditor.com/cke4/addon/htmlwriter) plugin was removed in https://github.com/liferay/liferay-ckeditor/commit/cc4b314b87885823eee05a4021f6d17a5c43c158

We solved the line break issue in ckeditor by importing js-beautify library when the new source editor plugin was introduced in [LPS-118290](https://issues.liferay.com/browse/LPS-118290)

I intended to resolve the issue in alloyeditor with the same approach, but simply restoring htmlwriter in our ckeditor resolves the issue.

**Comment by wincent** [comment]
See also: https://github.com/liferay/liferay-ckeditor/pull/152

**Comment by julien** [comment]
Fixed in #152
