### ISSUE TITLE
removeListener() may be called on an undefined object

### ISSUE THREAD

**Issue by IstvanD** [liferay/liferay-ckeditor#166]
Calling removeListener() may lead to an exception because the `me` object can be null/undefined.
https://github.com/ckeditor/ckeditor4/blob/major/core/event.js#L167

This may lead to issues like [LPS-131699](https://issues.liferay.com/browse/LPS-131699).

See [PTR-2398](https://issues.liferay.com/browse/PTR-2398) for more info and explanation.

A null check should be applied.

**Comment by julien** [comment]
Fixed by #168
