### ISSUE TITLE
Update to v4.21

### ISSUE THREAD

**Issue by fortunatomaldonado** [liferay/liferay-ckeditor#205]
https://liferay.atlassian.net/browse/LPS-196513

Currently we are using v4.18 and we need to update to v4.21.
More information can be found in the LPS-196513

**Comment by markocikos** [comment]
Published: https://www.npmjs.com/package/liferay-ckeditor/v/4.21.0-liferay.1. 

@fortunatomaldonado We can now update version in DXP.
